name: release

on:
  push:
    tags:
      - "hot-reload-agent-all-*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8]
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }} 
      - name: Build with Maven
        run: mvn clean package -P full -Dmaven.test.skip=true

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            packaging/target/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

